// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaVrjnXkkQdaqPuPIreqP-Hjc_7J_gMSo',
    appId: '1:1023828266092:web:6890309a2e81dd2e659c49',
    messagingSenderId: '1023828266092',
    projectId: 'testing-99a42',
    authDomain: 'testing-99a42.firebaseapp.com',
    storageBucket: 'testing-99a42.firebasestorage.app',
    measurementId: 'G-J249JFZGME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG_xmUD6lwo-maTAW_3iTN3lTq8lZnxCA',
    appId: '1:1023828266092:android:d8582a1b247b7ec9659c49',
    messagingSenderId: '1023828266092',
    projectId: 'testing-99a42',
    storageBucket: 'testing-99a42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyq-wlI5meKydjtTUdIDiv7xD4nrajEdU',
    appId: '1:1023828266092:ios:ec55ca47a4fa1dbd659c49',
    messagingSenderId: '1023828266092',
    projectId: 'testing-99a42',
    storageBucket: 'testing-99a42.firebasestorage.app',
    iosClientId:
        '1023828266092-tbchh39gmb2c0q16ppaeqg589hn59jb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.authtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaVrjnXkkQdaqPuPIreqP-Hjc_7J_gMSo',
    appId: '1:1023828266092:web:8564eee662dae2d6659c49',
    messagingSenderId: '1023828266092',
    projectId: 'testing-99a42',
    authDomain: 'testing-99a42.firebaseapp.com',
    storageBucket: 'testing-99a42.firebasestorage.app',
    measurementId: 'G-J2YTNW313K',
  );
}
